[phases.build]
cmds = [
  "npm install",
  "npm run build-all",
  "pip install -r requirements.txt"
]

[phases.setup]
nixPkgs = ["nodejs", "npm", "python3", "python3Packages.pip"]

[start]
cmd = "gunicorn main:app --bind 0.0.0.0:$PORT"

[variables]
FLASK_ENV = "production"
FLASK_APP = "main.py"